version: '3.7'

services:
  analyze:
    image: analyze
    build:
      context: ./docker/analyze
      dockerfile: Dockerfile
    volumes:
      - .:/app

  style:
    image: style
    build:
      context: ./docker/style
      dockerfile: Dockerfile
    volumes:
      - .:/data

  app:
    image: app
    build:
      context: docker/app
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
