FROM ghcr.io/phpstan/phpstan:latest

RUN composer global require phpstan/phpstan-phpunit
RUN composer global require phpstan/phpstan-mockery
RUN composer global require phpstan/phpstan-deprecation-rules
RUN composer global require nunomaduro/larastan
RUN composer global require thecodingmachine/phpstan-safe-rule
